// Code generated by protoc-gen-go-proxy. DO NOT EDIT.
// source: adviser.proto

package proxypb

import (
	"context"

	"github.com/effective-security/porto/pkg/retriable"
	"github.com/effective-security/porto/xhttp/correlation"
	"github.com/effective-security/porto/xhttp/httperror"
	"github.com/effective-security/promptviser/api/pb"
	"google.golang.org/grpc"
)

type proxyAdviserServer struct {
	srv pb.AdviserServer
}

type proxyAdviserClient struct {
	remote   pb.AdviserClient
	callOpts []grpc.CallOption
}

type postproxyAdviserClient struct {
	client retriable.PostRequester
}

// AdviserServerToClient returns pb.AdviserClient
func AdviserServerToClient(srv pb.AdviserServer) pb.AdviserClient {
	return &proxyAdviserServer{srv}
}

// NewAdviserClient returns instance of the AdviserClient
func NewAdviserClient(conn *grpc.ClientConn, callOpts []grpc.CallOption) pb.AdviserServer {
	return &proxyAdviserClient{
		remote:   pb.NewAdviserClient(conn),
		callOpts: callOpts,
	}
}

// NewAdviserClientFromProxy returns instance of AdviserClient
func NewAdviserClientFromProxy(proxy pb.AdviserClient) pb.AdviserServer {
	return &proxyAdviserClient{
		remote: proxy,
	}
}

// NewAdviserClientFromProxy returns instance of AdviserClient
func NewHTTPAdviserClient(client retriable.PostRequester) pb.AdviserServer {
	return &postproxyAdviserClient{
		client: client,
	}
}

// Submit data for analysis.
func (s *proxyAdviserServer) Submit(ctx context.Context, req *pb.SubmitRequest, opts ...grpc.CallOption) (*pb.SubmitResponse, error) {
	// add correlation ID to outgoing RPC calls
	ctx = correlation.WithMetaFromContext(ctx)
	res, err := s.srv.Submit(ctx, req)
	if err != nil {
		return nil, httperror.NewFromPb(err)
	}
	return res, nil
}

// Submit data for analysis.
func (s *proxyAdviserClient) Submit(ctx context.Context, req *pb.SubmitRequest) (*pb.SubmitResponse, error) {
	// add correlation ID to outgoing RPC calls
	ctx = correlation.WithMetaFromContext(ctx)
	res, err := s.remote.Submit(ctx, req, s.callOpts...)
	if err != nil {
		return nil, httperror.NewFromPb(err)
	}
	return res, nil
}

// Submit data for analysis.
func (s *postproxyAdviserClient) Submit(ctx context.Context, req *pb.SubmitRequest) (*pb.SubmitResponse, error) {
	var res pb.SubmitResponse
	path := pb.Adviser_Submit_FullMethodName
	_, _, err := s.client.Post(ctx, path, req, &res)
	if err != nil {
		return nil, err
	}
	return &res, nil
}

// MatchRules evaluates anonymized dimension scores and static triggers against
// the rules database and returns matching findings. Prompt text never leaves
// the client — only numeric scores and metadata flags are sent.
func (s *proxyAdviserServer) MatchRules(ctx context.Context, req *pb.MatchRulesRequest, opts ...grpc.CallOption) (*pb.MatchRulesResponse, error) {
	// add correlation ID to outgoing RPC calls
	ctx = correlation.WithMetaFromContext(ctx)
	res, err := s.srv.MatchRules(ctx, req)
	if err != nil {
		return nil, httperror.NewFromPb(err)
	}
	return res, nil
}

// MatchRules evaluates anonymized dimension scores and static triggers against
// the rules database and returns matching findings. Prompt text never leaves
// the client — only numeric scores and metadata flags are sent.
func (s *proxyAdviserClient) MatchRules(ctx context.Context, req *pb.MatchRulesRequest) (*pb.MatchRulesResponse, error) {
	// add correlation ID to outgoing RPC calls
	ctx = correlation.WithMetaFromContext(ctx)
	res, err := s.remote.MatchRules(ctx, req, s.callOpts...)
	if err != nil {
		return nil, httperror.NewFromPb(err)
	}
	return res, nil
}

// MatchRules evaluates anonymized dimension scores and static triggers against
// the rules database and returns matching findings. Prompt text never leaves
// the client — only numeric scores and metadata flags are sent.
func (s *postproxyAdviserClient) MatchRules(ctx context.Context, req *pb.MatchRulesRequest) (*pb.MatchRulesResponse, error) {
	var res pb.MatchRulesResponse
	path := pb.Adviser_MatchRules_FullMethodName
	_, _, err := s.client.Post(ctx, path, req, &res)
	if err != nil {
		return nil, err
	}
	return &res, nil
}

// GetRules returns all rules so the client can cache them locally for
// offline Pass 1 evaluation.
func (s *proxyAdviserServer) GetRules(ctx context.Context, req *pb.GetRulesRequest, opts ...grpc.CallOption) (*pb.GetRulesResponse, error) {
	// add correlation ID to outgoing RPC calls
	ctx = correlation.WithMetaFromContext(ctx)
	res, err := s.srv.GetRules(ctx, req)
	if err != nil {
		return nil, httperror.NewFromPb(err)
	}
	return res, nil
}

// GetRules returns all rules so the client can cache them locally for
// offline Pass 1 evaluation.
func (s *proxyAdviserClient) GetRules(ctx context.Context, req *pb.GetRulesRequest) (*pb.GetRulesResponse, error) {
	// add correlation ID to outgoing RPC calls
	ctx = correlation.WithMetaFromContext(ctx)
	res, err := s.remote.GetRules(ctx, req, s.callOpts...)
	if err != nil {
		return nil, httperror.NewFromPb(err)
	}
	return res, nil
}

// GetRules returns all rules so the client can cache them locally for
// offline Pass 1 evaluation.
func (s *postproxyAdviserClient) GetRules(ctx context.Context, req *pb.GetRulesRequest) (*pb.GetRulesResponse, error) {
	var res pb.GetRulesResponse
	path := pb.Adviser_GetRules_FullMethodName
	_, _, err := s.client.Post(ctx, path, req, &res)
	if err != nil {
		return nil, err
	}
	return &res, nil
}

// GetStats returns aggregated rule-violation counts across all recorded scans.
func (s *proxyAdviserServer) GetStats(ctx context.Context, req *pb.GetStatsRequest, opts ...grpc.CallOption) (*pb.GetStatsResponse, error) {
	// add correlation ID to outgoing RPC calls
	ctx = correlation.WithMetaFromContext(ctx)
	res, err := s.srv.GetStats(ctx, req)
	if err != nil {
		return nil, httperror.NewFromPb(err)
	}
	return res, nil
}

// GetStats returns aggregated rule-violation counts across all recorded scans.
func (s *proxyAdviserClient) GetStats(ctx context.Context, req *pb.GetStatsRequest) (*pb.GetStatsResponse, error) {
	// add correlation ID to outgoing RPC calls
	ctx = correlation.WithMetaFromContext(ctx)
	res, err := s.remote.GetStats(ctx, req, s.callOpts...)
	if err != nil {
		return nil, httperror.NewFromPb(err)
	}
	return res, nil
}

// GetStats returns aggregated rule-violation counts across all recorded scans.
func (s *postproxyAdviserClient) GetStats(ctx context.Context, req *pb.GetStatsRequest) (*pb.GetStatsResponse, error) {
	var res pb.GetStatsResponse
	path := pb.Adviser_GetStats_FullMethodName
	_, _, err := s.client.Post(ctx, path, req, &res)
	if err != nil {
		return nil, err
	}
	return &res, nil
}
