// Code generated by protoc-gen-go-mock. DO NOT EDIT.
// source: adviser.proto

package mockpb

import (
	"context"

	"github.com/effective-security/promptviser/api/pb"
	"google.golang.org/protobuf/proto"
)

// MockAdviserServer for testing
type MockAdviserServer struct {
	pb.AdviserServer

	Reqs []proto.Message

	// If set, all calls return this error.
	Err error

	// responses to return if err == nil
	Resps []proto.Message
	Index int
}

// SetResponse sets a single response without errors
func (m *MockAdviserServer) SetResponse(r proto.Message) {
	m.Err = nil
	m.Resps = []proto.Message{r}
	m.Index = 0
}

// SetResponses sets responses without errors
func (m *MockAdviserServer) SetResponses(r []proto.Message) {
	m.Err = nil
	m.Resps = r
	m.Index = 0
}

func (m *MockAdviserServer) next() proto.Message {
	c := len(m.Resps)
	idx := m.Index
	m.Index++
	if idx >= c {
		idx = c - 1
	}
	return m.Resps[idx]
}

// Submit data for analysis.

func (m *MockAdviserServer) Submit(ctx context.Context, req *pb.SubmitRequest) (*pb.SubmitResponse, error) {
	if m.Err != nil {
		return nil, m.Err
	}
	return m.next().(*pb.SubmitResponse), nil
}

// MatchRules evaluates anonymized dimension scores and static triggers against
// the rules database and returns matching findings. Prompt text never leaves
// the client — only numeric scores and metadata flags are sent.

func (m *MockAdviserServer) MatchRules(ctx context.Context, req *pb.MatchRulesRequest) (*pb.MatchRulesResponse, error) {
	if m.Err != nil {
		return nil, m.Err
	}
	return m.next().(*pb.MatchRulesResponse), nil
}

// GetRules returns all rules so the client can cache them locally for
// offline Pass 1 evaluation.

func (m *MockAdviserServer) GetRules(ctx context.Context, req *pb.GetRulesRequest) (*pb.GetRulesResponse, error) {
	if m.Err != nil {
		return nil, m.Err
	}
	return m.next().(*pb.GetRulesResponse), nil
}

// GetStats returns aggregated rule-violation counts across all recorded scans.

func (m *MockAdviserServer) GetStats(ctx context.Context, req *pb.GetStatsRequest) (*pb.GetStatsResponse, error) {
	if m.Err != nil {
		return nil, m.Err
	}
	return m.next().(*pb.GetStatsResponse), nil
}
