// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: adviser.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/effective-security/protoc-gen-go/api"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_adviser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adviser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_adviser_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SubmitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the job ID.
	ID            string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_adviser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adviser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_adviser_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

// DimensionScore represents a single LLM-scored quality or risk dimension.
// Values are normalised floats in [0, 1].
type DimensionScore struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dimension is the name of the scoring dimension, e.g. "pii_exposure".
	Dimension string `protobuf:"bytes,1,opt,name=Dimension,proto3" json:"Dimension,omitempty"`
	// Score is the normalised value in [0, 1].
	Score         float32 `protobuf:"fixed32,2,opt,name=Score,proto3" json:"Score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DimensionScore) Reset() {
	*x = DimensionScore{}
	mi := &file_adviser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DimensionScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DimensionScore) ProtoMessage() {}

func (x *DimensionScore) ProtoReflect() protoreflect.Message {
	mi := &file_adviser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DimensionScore.ProtoReflect.Descriptor instead.
func (*DimensionScore) Descriptor() ([]byte, []int) {
	return file_adviser_proto_rawDescGZIP(), []int{2}
}

func (x *DimensionScore) GetDimension() string {
	if x != nil {
		return x.Dimension
	}
	return ""
}

func (x *DimensionScore) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type FileScanResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FileName is the relative path for reference only
	FileName string `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	// StaticTriggers lists rule IDs or named patterns that fired locally with regex
	StaticTriggers []string `protobuf:"bytes,2,rep,name=StaticTriggers,proto3" json:"StaticTriggers,omitempty"`
	// MetadataFlags carries boolean YAML metadata
	MetadataFlags []string `protobuf:"bytes,3,rep,name=MetadataFlags,proto3" json:"MetadataFlags,omitempty"`
	// ASTTriggers lists rule IDs or named patterns that fired based on AST analysis
	ASTTriggers []string `protobuf:"bytes,4,rep,name=ASTTriggers,proto3" json:"ASTTriggers,omitempty"`
	// Scores contains LLM-derived dimension scores
	Scores        []*DimensionScore `protobuf:"bytes,5,rep,name=Scores,proto3" json:"Scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileScanResult) Reset() {
	*x = FileScanResult{}
	mi := &file_adviser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileScanResult) ProtoMessage() {}

func (x *FileScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_adviser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileScanResult.ProtoReflect.Descriptor instead.
func (*FileScanResult) Descriptor() ([]byte, []int) {
	return file_adviser_proto_rawDescGZIP(), []int{3}
}

func (x *FileScanResult) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileScanResult) GetStaticTriggers() []string {
	if x != nil {
		return x.StaticTriggers
	}
	return nil
}

func (x *FileScanResult) GetMetadataFlags() []string {
	if x != nil {
		return x.MetadataFlags
	}
	return nil
}

func (x *FileScanResult) GetASTTriggers() []string {
	if x != nil {
		return x.ASTTriggers
	}
	return nil
}

func (x *FileScanResult) GetScores() []*DimensionScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

// MatchRulesRequest carries anonymised signals from the local scanner.
// No prompt text is included — only derived scores and metadata.
type MatchRulesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FileResults contains the aggregated results for all scanned files.
	FileResults   []*FileScanResult `protobuf:"bytes,1,rep,name=FileResults,proto3" json:"FileResults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRulesRequest) Reset() {
	*x = MatchRulesRequest{}
	mi := &file_adviser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRulesRequest) ProtoMessage() {}

func (x *MatchRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adviser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRulesRequest.ProtoReflect.Descriptor instead.
func (*MatchRulesRequest) Descriptor() ([]byte, []int) {
	return file_adviser_proto_rawDescGZIP(), []int{4}
}

func (x *MatchRulesRequest) GetFileResults() []*FileScanResult {
	if x != nil {
		return x.FileResults
	}
	return nil
}

// PromptFindings is the response for a single file, containing all matched rules.
type PromptFindings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FileName is the relative path for reference only
	FileName string `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	// Findings lists all matched rules with remediation guidance.
	Findings      []*Finding `protobuf:"bytes,2,rep,name=Findings,proto3" json:"Findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptFindings) Reset() {
	*x = PromptFindings{}
	mi := &file_adviser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptFindings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptFindings) ProtoMessage() {}

func (x *PromptFindings) ProtoReflect() protoreflect.Message {
	mi := &file_adviser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptFindings.ProtoReflect.Descriptor instead.
func (*PromptFindings) Descriptor() ([]byte, []int) {
	return file_adviser_proto_rawDescGZIP(), []int{5}
}

func (x *PromptFindings) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PromptFindings) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

// Finding is a single matched rule with remediation guidance.
type Finding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RuleID is the stable identifier, e.g. "PRIV-001".
	RuleID string `protobuf:"bytes,1,opt,name=RuleID,proto3" json:"RuleID,omitempty"`
	// Title is the human-readable name.
	Title string `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	// Severity is one of: Critical, High, Medium, Low.
	Severity string `protobuf:"bytes,3,opt,name=Severity,proto3" json:"Severity,omitempty"`
	// Domain is the rule category, e.g. "Data Privacy & Confidentiality".
	Domain string `protobuf:"bytes,4,opt,name=Domain,proto3" json:"Domain,omitempty"`
	// Remediation is the suggested fix text.
	Remediation string `protobuf:"bytes,5,opt,name=Remediation,proto3" json:"Remediation,omitempty"`
	// Standards lists applicable compliance references, e.g. "OWASP LLM01".
	Standards []string `protobuf:"bytes,6,rep,name=Standards,proto3" json:"Standards,omitempty"`
	// TriggerType is one of: static, score, meta, or combined.
	TriggerType   string `protobuf:"bytes,7,opt,name=TriggerType,proto3" json:"TriggerType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_adviser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_adviser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_adviser_proto_rawDescGZIP(), []int{6}
}

func (x *Finding) GetRuleID() string {
	if x != nil {
		return x.RuleID
	}
	return ""
}

func (x *Finding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Finding) GetRemediation() string {
	if x != nil {
		return x.Remediation
	}
	return ""
}

func (x *Finding) GetStandards() []string {
	if x != nil {
		return x.Standards
	}
	return nil
}

func (x *Finding) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

// MatchRulesResponse contains all rules that fired for the given input.
type MatchRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Findings      []*PromptFindings      `protobuf:"bytes,1,rep,name=Findings,json=PromptFindings,proto3" json:"Findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRulesResponse) Reset() {
	*x = MatchRulesResponse{}
	mi := &file_adviser_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRulesResponse) ProtoMessage() {}

func (x *MatchRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adviser_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRulesResponse.ProtoReflect.Descriptor instead.
func (*MatchRulesResponse) Descriptor() ([]byte, []int) {
	return file_adviser_proto_rawDescGZIP(), []int{7}
}

func (x *MatchRulesResponse) GetFindings() []*PromptFindings {
	if x != nil {
		return x.Findings
	}
	return nil
}

// GetRulesRequest allows optional domain or severity filtering.
type GetRulesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Domain filters by rule domain; empty means all domains.
	Domain string `protobuf:"bytes,1,opt,name=Domain,proto3" json:"Domain,omitempty"`
	// Severity filters by minimum severity; empty means all severities.
	Severity      string `protobuf:"bytes,2,opt,name=Severity,proto3" json:"Severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRulesRequest) Reset() {
	*x = GetRulesRequest{}
	mi := &file_adviser_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRulesRequest) ProtoMessage() {}

func (x *GetRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adviser_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRulesRequest.ProtoReflect.Descriptor instead.
func (*GetRulesRequest) Descriptor() ([]byte, []int) {
	return file_adviser_proto_rawDescGZIP(), []int{8}
}

func (x *GetRulesRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GetRulesRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

// GetRulesResponse returns the full rule catalogue.
type GetRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Finding             `protobuf:"bytes,1,rep,name=Rules,proto3" json:"Rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRulesResponse) Reset() {
	*x = GetRulesResponse{}
	mi := &file_adviser_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRulesResponse) ProtoMessage() {}

func (x *GetRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adviser_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRulesResponse.ProtoReflect.Descriptor instead.
func (*GetRulesResponse) Descriptor() ([]byte, []int) {
	return file_adviser_proto_rawDescGZIP(), []int{9}
}

func (x *GetRulesResponse) GetRules() []*Finding {
	if x != nil {
		return x.Rules
	}
	return nil
}

// GetStatsRequest carries optional parameters for the GetStats RPC.
type GetStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Limit is the maximum number of top violations to return. 0 = default (10).
	Limit         int32 `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_adviser_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adviser_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_adviser_proto_rawDescGZIP(), []int{10}
}

func (x *GetStatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// RuleViolationCount represents one rule's aggregated violation total.
type RuleViolationCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleID        string                 `protobuf:"bytes,1,opt,name=RuleID,proto3" json:"RuleID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=Severity,proto3" json:"Severity,omitempty"`
	Domain        string                 `protobuf:"bytes,4,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Standards     []string               `protobuf:"bytes,5,rep,name=Standards,proto3" json:"Standards,omitempty"`
	Count         int64                  `protobuf:"varint,6,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleViolationCount) Reset() {
	*x = RuleViolationCount{}
	mi := &file_adviser_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleViolationCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleViolationCount) ProtoMessage() {}

func (x *RuleViolationCount) ProtoReflect() protoreflect.Message {
	mi := &file_adviser_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleViolationCount.ProtoReflect.Descriptor instead.
func (*RuleViolationCount) Descriptor() ([]byte, []int) {
	return file_adviser_proto_rawDescGZIP(), []int{11}
}

func (x *RuleViolationCount) GetRuleID() string {
	if x != nil {
		return x.RuleID
	}
	return ""
}

func (x *RuleViolationCount) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RuleViolationCount) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *RuleViolationCount) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RuleViolationCount) GetStandards() []string {
	if x != nil {
		return x.Standards
	}
	return nil
}

func (x *RuleViolationCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetStatsResponse returns aggregated violation statistics.
type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopViolations []*RuleViolationCount  `protobuf:"bytes,1,rep,name=TopViolations,proto3" json:"TopViolations,omitempty"`
	TotalScans    int64                  `protobuf:"varint,2,opt,name=TotalScans,proto3" json:"TotalScans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_adviser_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adviser_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_adviser_proto_rawDescGZIP(), []int{12}
}

func (x *GetStatsResponse) GetTopViolations() []*RuleViolationCount {
	if x != nil {
		return x.TopViolations
	}
	return nil
}

func (x *GetStatsResponse) GetTotalScans() int64 {
	if x != nil {
		return x.TotalScans
	}
	return 0
}

var File_adviser_proto protoreflect.FileDescriptor

const file_adviser_proto_rawDesc = "" +
	"\n" +
	"\radviser.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x18es/api/annotations.proto\"#\n" +
	"\rSubmitRequest\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\tR\x04Data\" \n" +
	"\x0eSubmitResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"D\n" +
	"\x0eDimensionScore\x12\x1c\n" +
	"\tDimension\x18\x01 \x01(\tR\tDimension\x12\x14\n" +
	"\x05Score\x18\x02 \x01(\x02R\x05Score\"\xc8\x01\n" +
	"\x0eFileScanResult\x12\x1a\n" +
	"\bFileName\x18\x01 \x01(\tR\bFileName\x12&\n" +
	"\x0eStaticTriggers\x18\x02 \x03(\tR\x0eStaticTriggers\x12$\n" +
	"\rMetadataFlags\x18\x03 \x03(\tR\rMetadataFlags\x12 \n" +
	"\vASTTriggers\x18\x04 \x03(\tR\vASTTriggers\x12*\n" +
	"\x06Scores\x18\x05 \x03(\v2\x12.pb.DimensionScoreR\x06Scores\"I\n" +
	"\x11MatchRulesRequest\x124\n" +
	"\vFileResults\x18\x01 \x03(\v2\x12.pb.FileScanResultR\vFileResults\"U\n" +
	"\x0ePromptFindings\x12\x1a\n" +
	"\bFileName\x18\x01 \x01(\tR\bFileName\x12'\n" +
	"\bFindings\x18\x02 \x03(\v2\v.pb.FindingR\bFindings\"\xcd\x01\n" +
	"\aFinding\x12\x16\n" +
	"\x06RuleID\x18\x01 \x01(\tR\x06RuleID\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x1a\n" +
	"\bSeverity\x18\x03 \x01(\tR\bSeverity\x12\x16\n" +
	"\x06Domain\x18\x04 \x01(\tR\x06Domain\x12 \n" +
	"\vRemediation\x18\x05 \x01(\tR\vRemediation\x12\x1c\n" +
	"\tStandards\x18\x06 \x03(\tR\tStandards\x12 \n" +
	"\vTriggerType\x18\a \x01(\tR\vTriggerType\"J\n" +
	"\x12MatchRulesResponse\x124\n" +
	"\bFindings\x18\x01 \x03(\v2\x12.pb.PromptFindingsR\x0ePromptFindings\"E\n" +
	"\x0fGetRulesRequest\x12\x16\n" +
	"\x06Domain\x18\x01 \x01(\tR\x06Domain\x12\x1a\n" +
	"\bSeverity\x18\x02 \x01(\tR\bSeverity\"5\n" +
	"\x10GetRulesResponse\x12!\n" +
	"\x05Rules\x18\x01 \x03(\v2\v.pb.FindingR\x05Rules\"'\n" +
	"\x0fGetStatsRequest\x12\x14\n" +
	"\x05Limit\x18\x01 \x01(\x05R\x05Limit\"\xaa\x01\n" +
	"\x12RuleViolationCount\x12\x16\n" +
	"\x06RuleID\x18\x01 \x01(\tR\x06RuleID\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x1a\n" +
	"\bSeverity\x18\x03 \x01(\tR\bSeverity\x12\x16\n" +
	"\x06Domain\x18\x04 \x01(\tR\x06Domain\x12\x1c\n" +
	"\tStandards\x18\x05 \x03(\tR\tStandards\x12\x14\n" +
	"\x05Count\x18\x06 \x01(\x03R\x05Count\"p\n" +
	"\x10GetStatsResponse\x12<\n" +
	"\rTopViolations\x18\x01 \x03(\v2\x16.pb.RuleViolationCountR\rTopViolations\x12\x1e\n" +
	"\n" +
	"TotalScans\x18\x02 \x01(\x03R\n" +
	"TotalScans2\x98\x03\n" +
	"\aAdviser\x12W\n" +
	"\x06Submit\x12\x11.pb.SubmitRequest\x1a\x12.pb.SubmitResponse\"&\x82C\x06submit\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/pb.Adviser/Submit\x12l\n" +
	"\n" +
	"MatchRules\x12\x15.pb.MatchRulesRequest\x1a\x16.pb.MatchRulesResponse\"/\x82C\vmatch-rules\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/pb.Adviser/MatchRules\x12b\n" +
	"\bGetRules\x12\x13.pb.GetRulesRequest\x1a\x14.pb.GetRulesResponse\"+\x82C\tget-rules\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/pb.Adviser/GetRules\x12b\n" +
	"\bGetStats\x12\x13.pb.GetStatsRequest\x1a\x14.pb.GetStatsResponse\"+\x82C\tget-stats\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/pb.Adviser/GetStatsB2Z0github.com/effective-security/promptviser/api/pbb\x06proto3"

var (
	file_adviser_proto_rawDescOnce sync.Once
	file_adviser_proto_rawDescData []byte
)

func file_adviser_proto_rawDescGZIP() []byte {
	file_adviser_proto_rawDescOnce.Do(func() {
		file_adviser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adviser_proto_rawDesc), len(file_adviser_proto_rawDesc)))
	})
	return file_adviser_proto_rawDescData
}

var file_adviser_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_adviser_proto_goTypes = []any{
	(*SubmitRequest)(nil),      // 0: pb.SubmitRequest
	(*SubmitResponse)(nil),     // 1: pb.SubmitResponse
	(*DimensionScore)(nil),     // 2: pb.DimensionScore
	(*FileScanResult)(nil),     // 3: pb.FileScanResult
	(*MatchRulesRequest)(nil),  // 4: pb.MatchRulesRequest
	(*PromptFindings)(nil),     // 5: pb.PromptFindings
	(*Finding)(nil),            // 6: pb.Finding
	(*MatchRulesResponse)(nil), // 7: pb.MatchRulesResponse
	(*GetRulesRequest)(nil),    // 8: pb.GetRulesRequest
	(*GetRulesResponse)(nil),   // 9: pb.GetRulesResponse
	(*GetStatsRequest)(nil),    // 10: pb.GetStatsRequest
	(*RuleViolationCount)(nil), // 11: pb.RuleViolationCount
	(*GetStatsResponse)(nil),   // 12: pb.GetStatsResponse
}
var file_adviser_proto_depIdxs = []int32{
	2,  // 0: pb.FileScanResult.Scores:type_name -> pb.DimensionScore
	3,  // 1: pb.MatchRulesRequest.FileResults:type_name -> pb.FileScanResult
	6,  // 2: pb.PromptFindings.Findings:type_name -> pb.Finding
	5,  // 3: pb.MatchRulesResponse.Findings:type_name -> pb.PromptFindings
	6,  // 4: pb.GetRulesResponse.Rules:type_name -> pb.Finding
	11, // 5: pb.GetStatsResponse.TopViolations:type_name -> pb.RuleViolationCount
	0,  // 6: pb.Adviser.Submit:input_type -> pb.SubmitRequest
	4,  // 7: pb.Adviser.MatchRules:input_type -> pb.MatchRulesRequest
	8,  // 8: pb.Adviser.GetRules:input_type -> pb.GetRulesRequest
	10, // 9: pb.Adviser.GetStats:input_type -> pb.GetStatsRequest
	1,  // 10: pb.Adviser.Submit:output_type -> pb.SubmitResponse
	7,  // 11: pb.Adviser.MatchRules:output_type -> pb.MatchRulesResponse
	9,  // 12: pb.Adviser.GetRules:output_type -> pb.GetRulesResponse
	12, // 13: pb.Adviser.GetStats:output_type -> pb.GetStatsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_adviser_proto_init() }
func file_adviser_proto_init() {
	if File_adviser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adviser_proto_rawDesc), len(file_adviser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adviser_proto_goTypes,
		DependencyIndexes: file_adviser_proto_depIdxs,
		MessageInfos:      file_adviser_proto_msgTypes,
	}.Build()
	File_adviser_proto = out.File
	file_adviser_proto_goTypes = nil
	file_adviser_proto_depIdxs = nil
}
