// Code generated by protoc-gen-go-json. DO NOT EDIT.

package pb

import (
	context "context"
	"fmt"
	sync "sync"

	"github.com/effective-security/protoc-gen-go/api"
	"google.golang.org/protobuf/types/known/emptypb"
)

var Empty_MessageDescription = &api.MessageDescription{
	Name:     "Empty",
	FullName: "google.protobuf.Empty",
	Documentation: `A generic empty message that you can re-use to avoid defining duplicated
empty messages in your APIs. A typical example is to use it as the request
or the response type of an API method. For instance:
service Foo {
rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
}`,
	Fields: []*api.FieldMeta{},
}

var DimensionScore_MessageDescription = &api.MessageDescription{
	Name:     "DimensionScore",
	Display:  "Dimension Score",
	FullName: "pb.DimensionScore",
	Documentation: `DimensionScore represents a single LLM-scored quality or risk dimension.
Values are normalised floats in [0, 1].`,
	Fields: []*api.FieldMeta{
		{
			Name:          "Dimension",
			FullName:      "pb.DimensionScore.Dimension",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Dimension is the name of the scoring dimension, e.g. "pii_exposure".`,
		},
		{
			Name:          "Score",
			FullName:      "pb.DimensionScore.Score",
			Type:          "float32",
			SearchType:    "float",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Score is the normalised value in [0, 1].`,
		},
	},
}

var FileScanResult_MessageDescription = &api.MessageDescription{
	Name:     "FileScanResult",
	Display:  "File Scan Result",
	FullName: "pb.FileScanResult",
	Fields: []*api.FieldMeta{
		{
			Name:          "FileName",
			FullName:      "pb.FileScanResult.FileName",
			Display:       "File Name",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `FileName is the relative path for reference only`,
		},
		{
			Name:          "StaticTriggers",
			FullName:      "pb.FileScanResult.StaticTriggers",
			Display:       "Static Triggers",
			Type:          "[]string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `StaticTriggers lists rule IDs or named patterns that fired locally with regex`,
		},
		{
			Name:          "MetadataFlags",
			FullName:      "pb.FileScanResult.MetadataFlags",
			Display:       "Metadata Flags",
			Type:          "[]string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `MetadataFlags carries boolean YAML metadata`,
		},
		{
			Name:          "ASTTriggers",
			FullName:      "pb.FileScanResult.ASTTriggers",
			Display:       "AST Triggers",
			Type:          "[]string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `ASTTriggers lists rule IDs or named patterns that fired based on AST analysis`,
		},
		{
			Name:          "Scores",
			FullName:      "pb.FileScanResult.Scores",
			Type:          "[]struct",
			StructName:    "pb.DimensionScore",
			SearchType:    "flat_object",
			Documentation: `Scores contains LLM-derived dimension scores`,
		},
	},
}

var Finding_MessageDescription = &api.MessageDescription{
	Name:          "Finding",
	FullName:      "pb.Finding",
	Documentation: `Finding is a single matched rule with remediation guidance.`,
	Fields: []*api.FieldMeta{
		{
			Name:          "RuleID",
			FullName:      "pb.Finding.RuleID",
			Display:       "Rule ID",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `RuleID is the stable identifier, e.g. "PRIV-001".`,
		},
		{
			Name:          "Title",
			FullName:      "pb.Finding.Title",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Title is the human-readable name.`,
		},
		{
			Name:          "Severity",
			FullName:      "pb.Finding.Severity",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Severity is one of: Critical, High, Medium, Low.`,
		},
		{
			Name:          "Domain",
			FullName:      "pb.Finding.Domain",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Domain is the rule category, e.g. "Data Privacy & Confidentiality".`,
		},
		{
			Name:          "Remediation",
			FullName:      "pb.Finding.Remediation",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Remediation is the suggested fix text.`,
		},
		{
			Name:          "Standards",
			FullName:      "pb.Finding.Standards",
			Type:          "[]string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Standards lists applicable compliance references, e.g. "OWASP LLM01".`,
		},
		{
			Name:          "TriggerType",
			FullName:      "pb.Finding.TriggerType",
			Display:       "Trigger Type",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `TriggerType is one of: static, score, meta, or combined.`,
		},
	},
}

var GetRulesRequest_MessageDescription = &api.MessageDescription{
	Name:          "GetRulesRequest",
	Display:       "Get Rules Request",
	FullName:      "pb.GetRulesRequest",
	Documentation: `GetRulesRequest allows optional domain or severity filtering.`,
	Fields: []*api.FieldMeta{
		{
			Name:          "Domain",
			FullName:      "pb.GetRulesRequest.Domain",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Domain filters by rule domain; empty means all domains.`,
		},
		{
			Name:          "Severity",
			FullName:      "pb.GetRulesRequest.Severity",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Severity filters by minimum severity; empty means all severities.`,
		},
	},
}

var GetRulesResponse_MessageDescription = &api.MessageDescription{
	Name:          "GetRulesResponse",
	Display:       "Get Rules Response",
	FullName:      "pb.GetRulesResponse",
	Documentation: `GetRulesResponse returns the full rule catalogue.`,
	Fields: []*api.FieldMeta{
		{
			Name:       "Rules",
			FullName:   "pb.GetRulesResponse.Rules",
			Type:       "[]struct",
			StructName: "pb.Finding",
			SearchType: "flat_object",
		},
	},
}

var GetStatsRequest_MessageDescription = &api.MessageDescription{
	Name:          "GetStatsRequest",
	Display:       "Get Stats Request",
	FullName:      "pb.GetStatsRequest",
	Documentation: `GetStatsRequest carries optional parameters for the GetStats RPC.`,
	Fields: []*api.FieldMeta{
		{
			Name:          "Limit",
			FullName:      "pb.GetStatsRequest.Limit",
			Type:          "int32",
			SearchType:    "integer",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Limit is the maximum number of top violations to return. 0 = default (10).`,
		},
	},
}

var GetStatsResponse_MessageDescription = &api.MessageDescription{
	Name:          "GetStatsResponse",
	Display:       "Get Stats Response",
	FullName:      "pb.GetStatsResponse",
	Documentation: `GetStatsResponse returns aggregated violation statistics.`,
	Fields: []*api.FieldMeta{
		{
			Name:       "TopViolations",
			FullName:   "pb.GetStatsResponse.TopViolations",
			Display:    "Top Violations",
			Type:       "[]struct",
			StructName: "pb.RuleViolationCount",
			SearchType: "flat_object",
		},
		{
			Name:          "TotalScans",
			FullName:      "pb.GetStatsResponse.TotalScans",
			Display:       "Total Scans",
			Type:          "int64",
			SearchType:    "integer",
			SearchOptions: api.SearchOption_Sortable,
		},
	},
}

var MatchRulesRequest_MessageDescription = &api.MessageDescription{
	Name:     "MatchRulesRequest",
	Display:  "Match Rules Request",
	FullName: "pb.MatchRulesRequest",
	Documentation: `MatchRulesRequest carries anonymised signals from the local scanner.
No prompt text is included — only derived scores and metadata.`,
	Fields: []*api.FieldMeta{
		{
			Name:          "FileResults",
			FullName:      "pb.MatchRulesRequest.FileResults",
			Display:       "File Results",
			Type:          "[]struct",
			StructName:    "pb.FileScanResult",
			SearchType:    "flat_object",
			Documentation: `FileResults contains the aggregated results for all scanned files.`,
		},
	},
}

var MatchRulesResponse_MessageDescription = &api.MessageDescription{
	Name:          "MatchRulesResponse",
	Display:       "Match Rules Response",
	FullName:      "pb.MatchRulesResponse",
	Documentation: `MatchRulesResponse contains all rules that fired for the given input.`,
	Fields: []*api.FieldMeta{
		{
			Name:       "Findings",
			FullName:   "pb.MatchRulesResponse.Findings",
			Type:       "[]struct",
			StructName: "pb.PromptFindings",
			SearchType: "flat_object",
		},
	},
}

var PromptFindings_MessageDescription = &api.MessageDescription{
	Name:          "PromptFindings",
	Display:       "Prompt Findings",
	FullName:      "pb.PromptFindings",
	Documentation: `PromptFindings is the response for a single file, containing all matched rules.`,
	Fields: []*api.FieldMeta{
		{
			Name:          "FileName",
			FullName:      "pb.PromptFindings.FileName",
			Display:       "File Name",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `FileName is the relative path for reference only`,
		},
		{
			Name:          "Findings",
			FullName:      "pb.PromptFindings.Findings",
			Type:          "[]struct",
			StructName:    "pb.Finding",
			SearchType:    "flat_object",
			Documentation: `Findings lists all matched rules with remediation guidance.`,
		},
	},
}

var RuleViolationCount_MessageDescription = &api.MessageDescription{
	Name:          "RuleViolationCount",
	Display:       "Rule Violation Count",
	FullName:      "pb.RuleViolationCount",
	Documentation: `RuleViolationCount represents one rule's aggregated violation total.`,
	Fields: []*api.FieldMeta{
		{
			Name:          "RuleID",
			FullName:      "pb.RuleViolationCount.RuleID",
			Display:       "Rule ID",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
		},
		{
			Name:          "Title",
			FullName:      "pb.RuleViolationCount.Title",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
		},
		{
			Name:          "Severity",
			FullName:      "pb.RuleViolationCount.Severity",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
		},
		{
			Name:          "Domain",
			FullName:      "pb.RuleViolationCount.Domain",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
		},
		{
			Name:          "Standards",
			FullName:      "pb.RuleViolationCount.Standards",
			Type:          "[]string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
		},
		{
			Name:          "Count",
			FullName:      "pb.RuleViolationCount.Count",
			Type:          "int64",
			SearchType:    "integer",
			SearchOptions: api.SearchOption_Sortable,
		},
	},
}

var ServerStatus_MessageDescription = &api.MessageDescription{
	Name:          "ServerStatus",
	Display:       "Server Status",
	FullName:      "pb.ServerStatus",
	Documentation: `ServerStatus provides server status information`,
	Fields: []*api.FieldMeta{
		{
			Name:          "Name",
			FullName:      "pb.ServerStatus.Name",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Name of the server or application.`,
		},
		{
			Name:          "Nodename",
			FullName:      "pb.ServerStatus.Nodename",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Nodename is the human-readable name of the cluster member,
or empty for single host.`,
		},
		{
			Name:          "Hostname",
			FullName:      "pb.ServerStatus.Hostname",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Hostname is operating system's host name.`,
		},
		{
			Name:          "ListenUrls",
			FullName:      "pb.ServerStatus.ListenUrls",
			Display:       "Listen Urls",
			Type:          "[]string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `ListenURLs is the list of URLs the service is listening on.`,
		},
		{
			Name:          "StartedAt",
			FullName:      "pb.ServerStatus.StartedAt",
			Display:       "Started At",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `StartedAt is the time in RFC3339 format.`,
		},
	},
}

var ServerStatusResponse_MessageDescription = &api.MessageDescription{
	Name:          "ServerStatusResponse",
	Display:       "Server Status Response",
	FullName:      "pb.ServerStatusResponse",
	Documentation: `ServerStatusResponse returns status and version`,
	Fields: []*api.FieldMeta{
		{
			Name:          "Status",
			FullName:      "pb.ServerStatusResponse.Status",
			Type:          "struct",
			StructName:    "pb.ServerStatus",
			SearchType:    "flat_object",
			Documentation: `Status of the server.`,
		},
		{
			Name:          "Version",
			FullName:      "pb.ServerStatusResponse.Version",
			Type:          "struct",
			StructName:    "pb.ServerVersion",
			SearchType:    "flat_object",
			Documentation: `Version of the server.`,
		},
		{
			Name:       "Pods",
			FullName:   "pb.ServerStatusResponse.Pods",
			Type:       "map",
			StructName: "pb.ServerStatusResponse.PodsEntry",
			SearchType: "flat_object",
		},
	},
}

var ServerStatusResponse_PodsEntry_MessageDescription = &api.MessageDescription{
	Name:     "ServerStatusResponse_PodsEntry",
	Display:  "Pods Entry",
	FullName: "pb.ServerStatusResponse.PodsEntry",
	Fields: []*api.FieldMeta{
		{
			Name:          "Key",
			FullName:      "pb.ServerStatusResponse.PodsEntry.Key",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Required:      true,
		},
		{
			Name:          "Value",
			FullName:      "pb.ServerStatusResponse.PodsEntry.Value",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Required:      true,
		},
	},
}

var ServerVersion_MessageDescription = &api.MessageDescription{
	Name:          "ServerVersion",
	Display:       "Server Version",
	FullName:      "pb.ServerVersion",
	Documentation: `ServerVersion provides server build and runtime version`,
	Fields: []*api.FieldMeta{
		{
			Name:          "Build",
			FullName:      "pb.ServerVersion.Build",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Build is the server build version.`,
		},
		{
			Name:          "Runtime",
			FullName:      "pb.ServerVersion.Runtime",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Runtime is the runtime version.`,
		},
	},
}

var SubmitRequest_MessageDescription = &api.MessageDescription{
	Name:     "SubmitRequest",
	Display:  "Submit Request",
	FullName: "pb.SubmitRequest",
	Fields: []*api.FieldMeta{
		{
			Name:          "Data",
			FullName:      "pb.SubmitRequest.Data",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
		},
	},
}

var SubmitResponse_MessageDescription = &api.MessageDescription{
	Name:     "SubmitResponse",
	Display:  "Submit Response",
	FullName: "pb.SubmitResponse",
	Fields: []*api.FieldMeta{
		{
			Name:          "ID",
			FullName:      "pb.SubmitResponse.ID",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `ID is the job ID.`,
		},
	},
}

// MessageAllocator defines constructor to allocate Protobuf message
type MessageAllocator func() any

var (
	initMessageDescriptionOnce sync.Once
	messageDescriptions        = map[string]*api.MessageDescription{
		"google.protobuf.Empty":             Empty_MessageDescription,
		"pb.DimensionScore":                 DimensionScore_MessageDescription,
		"pb.FileScanResult":                 FileScanResult_MessageDescription,
		"pb.Finding":                        Finding_MessageDescription,
		"pb.GetRulesRequest":                GetRulesRequest_MessageDescription,
		"pb.GetRulesResponse":               GetRulesResponse_MessageDescription,
		"pb.GetStatsRequest":                GetStatsRequest_MessageDescription,
		"pb.GetStatsResponse":               GetStatsResponse_MessageDescription,
		"pb.MatchRulesRequest":              MatchRulesRequest_MessageDescription,
		"pb.MatchRulesResponse":             MatchRulesResponse_MessageDescription,
		"pb.PromptFindings":                 PromptFindings_MessageDescription,
		"pb.RuleViolationCount":             RuleViolationCount_MessageDescription,
		"pb.ServerStatus":                   ServerStatus_MessageDescription,
		"pb.ServerStatusResponse":           ServerStatusResponse_MessageDescription,
		"pb.ServerStatusResponse.PodsEntry": ServerStatusResponse_PodsEntry_MessageDescription,
		"pb.ServerVersion":                  ServerVersion_MessageDescription,
		"pb.SubmitRequest":                  SubmitRequest_MessageDescription,
		"pb.SubmitResponse":                 SubmitResponse_MessageDescription,
	}

	messageAllocators = map[string]MessageAllocator{
		"google.protobuf.Empty":             func() any { return new(emptypb.Empty) },
		"pb.DimensionScore":                 func() any { return new(DimensionScore) },
		"pb.FileScanResult":                 func() any { return new(FileScanResult) },
		"pb.Finding":                        func() any { return new(Finding) },
		"pb.GetRulesRequest":                func() any { return new(GetRulesRequest) },
		"pb.GetRulesResponse":               func() any { return new(GetRulesResponse) },
		"pb.GetStatsRequest":                func() any { return new(GetStatsRequest) },
		"pb.GetStatsResponse":               func() any { return new(GetStatsResponse) },
		"pb.MatchRulesRequest":              func() any { return new(MatchRulesRequest) },
		"pb.MatchRulesResponse":             func() any { return new(MatchRulesResponse) },
		"pb.PromptFindings":                 func() any { return new(PromptFindings) },
		"pb.RuleViolationCount":             func() any { return new(RuleViolationCount) },
		"pb.ServerStatus":                   func() any { return new(ServerStatus) },
		"pb.ServerStatusResponse":           func() any { return new(ServerStatusResponse) },
		"pb.ServerStatusResponse.PodsEntry": func() any { return make(map[string]string) },
		"pb.ServerVersion":                  func() any { return new(ServerVersion) },
		"pb.SubmitRequest":                  func() any { return new(SubmitRequest) },
		"pb.SubmitResponse":                 func() any { return new(SubmitResponse) },
	}
)

func (m *GetRulesRequest) Validate(ctx context.Context) error {
	return api.ValidateRequest(ctx, m, GetRulesRequest_MessageDescription)
}
func (m *GetStatsRequest) Validate(ctx context.Context) error {
	return api.ValidateRequest(ctx, m, GetStatsRequest_MessageDescription)
}
func (m *MatchRulesRequest) Validate(ctx context.Context) error {
	return api.ValidateRequest(ctx, m, MatchRulesRequest_MessageDescription)
}
func (m *SubmitRequest) Validate(ctx context.Context) error {
	return api.ValidateRequest(ctx, m, SubmitRequest_MessageDescription)
}
func (m *GetRulesResponse) GetMessageDescription() *api.MessageDescription {
	return GetRulesResponse_MessageDescription
}
func (m *GetStatsResponse) GetMessageDescription() *api.MessageDescription {
	return GetStatsResponse_MessageDescription
}
func (m *MatchRulesResponse) GetMessageDescription() *api.MessageDescription {
	return MatchRulesResponse_MessageDescription
}
func (m *ServerStatusResponse) GetMessageDescription() *api.MessageDescription {
	return ServerStatusResponse_MessageDescription
}
func (m *ServerVersion) GetMessageDescription() *api.MessageDescription {
	return ServerVersion_MessageDescription
}
func (m *SubmitResponse) GetMessageDescription() *api.MessageDescription {
	return SubmitResponse_MessageDescription
}

func GetMessageDescriptions() map[string]*api.MessageDescription {
	// Update the message Fields with the nested messages
	initMessageDescriptionOnce.Do(func() {
		for _, md := range messageDescriptions {
			for _, field := range md.Fields {
				if field.Fields == nil && (field.Type == "struct" || field.Type == "[]struct" || field.Type == "object" || field.Type == "[]object") {
					if msgDescr, ok := messageDescriptions[field.StructName]; ok {
						field.Fields = msgDescr.Fields
					}
				}
			}
		}
	})
	return messageDescriptions
}

func CreateMessage(fullname string) any {
	allocator := messageAllocators[fullname]
	if allocator == nil {
		panic(fmt.Sprintf("allocator for %s not found", fullname))
	}
	return allocator()
}

func GetMessageDescription(fullname string) *api.MessageDescription {
	return GetMessageDescriptions()[fullname]
}

func init() {
	_ = GetMessageDescriptions()
}
